from github import Github

# The version is stored in `_version.py`, which is generated by
# `setuptools_scm` when the package is created.
from ._version import __version__


def create_branch(github_token, branch_name, repository, sha):
    """Create a branch on GitHub with the given name"""
    g = Github(github_token)
    repo = g.get_repo(repository)
    repo.create_git_ref(f"refs/heads/{branch_name}", sha)
